import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { logger } from '../utils/logger.js';
import { getReport } from './supabase.js';

const PDF_TEMP_DIR = process.env.PDF_TEMP_DIR || './tmp/pdfs';

// Ensure temp directory exists
if (!fs.existsSync(PDF_TEMP_DIR)) {
  fs.mkdirSync(PDF_TEMP_DIR, { recursive: true });
}

/**
 * Generate a PDF report from report data
 */
export async function generateReportPDF(reportId: string): Promise<Buffer> {
  try {
    // Fetch report data from database
    const report = await getReport(reportId);

    if (!report) {
      throw new Error('Report not found');
    }

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'letter',
        margin: 50,
      });

      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);

      // Header
      doc.fontSize(24).font('Helvetica-Bold').text('Property Valuation Report', {
        align: 'center',
      });

      doc.fontSize(12).font('Helvetica').text('Appraisal Online', {
        align: 'center',
      });

      doc.moveDown();

      // AI Disclaimer
      doc.fontSize(10).fillColor('#DC2626').text('⚠️ IMPORTANT DISCLAIMER', {
        align: 'left',
        underline: true,
      });

      doc.fontSize(9).fillColor('#000000').text(
        'This is a computer-generated estimate. It is NOT a licensed appraisal. Banks, courts, government agencies, ' +
        'and financial institutions do NOT accept this valuation as formal property appraisal.',
        {
          align: 'left',
          lineGap: 5,
        }
      );

      doc.moveDown();

      // Property Information
      doc.fontSize(12).font('Helvetica-Bold').text('Property Information', {
        underline: true,
      });

      doc.fontSize(10).font('Helvetica');
      doc.text(`Address: ${report.address}`);
      doc.text(`Bedrooms: ${report.bedrooms}`);
      doc.text(`Bathrooms: ${report.bathrooms}`);
      doc.text(`Square Feet: ${report.square_feet}`);
      doc.text(`Year Built: ${report.year_built}`);
      doc.text(`Property Type: ${report.property_type}`);
      doc.text(`Condition: ${report.condition}`);

      doc.moveDown();

      // Valuation
      doc.fontSize(12).font('Helvetica-Bold').text('Estimated Valuation', {
        underline: true,
      });

      const estimatedValue = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        maximumFractionDigits: 0,
      }).format(report.estimated_value / 100);

      const lowEstimate = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        maximumFractionDigits: 0,
      }).format(report.confidence_range.low / 100);

      const highEstimate = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        maximumFractionDigits: 0,
      }).format(report.confidence_range.high / 100);

      doc.fontSize(16).font('Helvetica-Bold').fillColor('#2563EB').text(estimatedValue, {
        align: 'center',
      });

      doc.fontSize(10).fillColor('#000000').text(
        `Estimated Range: ${lowEstimate} - ${highEstimate}`,
        {
          align: 'center',
        }
      );

      doc.moveDown();

      // Comparable Sales
      doc.fontSize(12).font('Helvetica-Bold').text('Comparable Sales', {
        underline: true,
      });

      if (report.comparables && report.comparables.length > 0) {
        doc.fontSize(9).font('Helvetica');

        report.comparables.forEach((comp: any, index: number) => {
          doc.text(`${index + 1}. ${comp.address}`);
          doc.text(
            `   Sale Price: $${(comp.sale_price / 100).toLocaleString()} | ` +
            `Date: ${comp.sale_date} | ` +
            `Similarity: ${(comp.similarity_score * 100).toFixed(0)}%`
          );
          doc.text(`   Distance: ${comp.distance_miles.toFixed(1)} miles`);
          doc.moveDown(0.3);
        });
      } else {
        doc.text('No comparable sales data available');
      }

      doc.moveDown();

      // Report Metadata
      doc.fontSize(8).fillColor('#6B7280').text(
        `Report ID: ${reportId} | Generated: ${new Date().toLocaleString()}`,
        {
          align: 'right',
        }
      );

      doc.fontSize(7).text(
        'This report was generated by Appraisal Online. For more information, visit www.appraisalonline.com',
        {
          align: 'center',
          color: '#9CA3AF',
        }
      );

      // Finalize PDF
      doc.end();
    });
  } catch (error) {
    logger.error('Error generating PDF:', error);
    throw error;
  }
}

/**
 * Save PDF to temp storage
 */
export async function savePDF(reportId: string, pdfBuffer: Buffer): Promise<string> {
  try {
    const fileName = `report-${reportId}-${Date.now()}.pdf`;
    const filePath = path.join(PDF_TEMP_DIR, fileName);

    fs.writeFileSync(filePath, pdfBuffer);

    logger.info(`PDF saved: ${filePath}`);

    return filePath;
  } catch (error) {
    logger.error('Error saving PDF:', error);
    throw error;
  }
}

/**
 * Delete PDF from temp storage
 */
export function deletePDF(filePath: string): void {
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      logger.info(`PDF deleted: ${filePath}`);
    }
  } catch (error) {
    logger.error('Error deleting PDF:', error);
  }
}
